# Generated by Django 4.1.5 on 2023-02-03 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0002_emailuser_remove_user_email"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="emailuser",
            table="email_users",
        ),
    ]
