# Generated by Django 4.1.6 on 2023-02-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth_app', '0004_emailuser_user_user_last_login_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='유저의 이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
