# Generated by Django 4.1.5 on 2023-02-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성 시각'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='글 삭제 여부'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='공개 여부'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='갱신 시각'),
        ),
    ]
