# Generated by Django 4.1.5 on 2023-02-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0008_alter_post_created_at_alter_post_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="글 삭제 여부"),
        ),
    ]
