# Generated by Django 4.1.5 on 2023-02-23 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="유저의 이메일"
                    ),
                ),
                ("username", models.CharField(max_length=254, unique=True)),
                (
                    "signup_method",
                    models.CharField(
                        choices=[("EM", "EMAIL")], default="EM", max_length=2
                    ),
                ),
                ("picture_url", models.URLField()),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="갱신 시각"),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="글 제목")),
                ("content", models.TextField(verbose_name="글 내용")),
                ("is_public", models.BooleanField(default=True, verbose_name="공개 여부")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="글 삭제 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="생성 시각"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="갱신 시각"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graphql_app.user",
                        verbose_name="글쓴이",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(max_length=20, unique=True, verbose_name="닉네임"),
                ),
                (
                    "introduction",
                    models.TextField(
                        blank=True, default="자기 소개가 없습니다.", verbose_name="소개"
                    ),
                ),
                ("is_public", models.BooleanField(default=True, verbose_name="공개 여부")),
                (
                    "gender",
                    models.CharField(
                        choices=[("NO", "미입력"), ("ML", "남성"), ("FM", "여성")],
                        default=None,
                        max_length=2,
                        null=True,
                        verbose_name="성별",
                    ),
                ),
                (
                    "age_group",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, " 10"),
                            (2, " 20"),
                            (3, " 30"),
                            (4, " 40"),
                            (5, " 50"),
                            (6, "Elder"),
                        ],
                        default=None,
                        null=True,
                        verbose_name="연령대",
                    ),
                ),
                (
                    "job",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=15,
                        null=True,
                        verbose_name="직업",
                    ),
                ),
                (
                    "is_certified",
                    models.BooleanField(default=False, verbose_name="공인 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="갱신 시각"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graphql_app.user",
                        verbose_name="대상 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "구독 페르소나",
                "verbose_name_plural": "구독 페르소나 목록",
                "db_table": "personas",
            },
        ),
        migrations.CreateModel(
            name="EmailUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="유저의 이메일"
                    ),
                ),
                ("password", models.TextField(verbose_name="유저의 비밀번호")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="갱신 시각"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graphql_app.user",
                    ),
                ),
            ],
            options={
                "db_table": "email_users",
            },
        ),
    ]
