# Generated by Django 4.1.5 on 2023-02-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graphql_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persona",
            name="age_group",
            field=models.PositiveIntegerField(
                default=None, null=True, verbose_name="나이"
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="gender",
            field=models.CharField(
                choices=[("ML", "남성"), ("FM", "여성")],
                default=None,
                max_length=2,
                null=True,
                verbose_name="성별",
            ),
        ),
    ]
