# Generated by Django 4.1.5 on 2023-02-28 23:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graphql_app", "0002_alter_persona_age_group_alter_persona_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="persona",
            old_name="age_group",
            new_name="age",
        ),
    ]
