# Generated by Django 4.1.5 on 2023-03-01 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graphql_app", "0002_rename_user_id_post_user"),
        ("graphql_app", "0004_alter_persona_age_alter_persona_gender"),
    ]

    operations = []
