# Generated by Django 4.1.5 on 2023-03-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0006_alter_persona_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=20, unique=True, verbose_name='태그 본문')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그 목록',
                'db_table': 'tags',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='preferred_tags',
            field=models.ManyToManyField(related_name='preferred_users', to='graphql_app.tag', verbose_name='선호 태그 목록'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='related_posts', to='graphql_app.tag', verbose_name='연관 태그 목록'),
        ),
    ]
