# Generated by Django 4.1.5 on 2023-03-04 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0007_tag_persona_preferred_tags_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성 시각'),
            preserve_default=False,
        ),
    ]
