# Generated by Django 4.1.5 on 2023-03-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0008_tag_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailUser',
        ),
    ]
