# Generated by Django 4.1.5 on 2023-03-06 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0009_delete_emailuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='persona',
            name='owner',
            field=models.ForeignKey(db_column='owner_user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='대상 사용자'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(db_column='author_persona_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='graphql_app.persona', verbose_name='글쓴이'),
            preserve_default=False,
        ),
    ]
