# Generated by Django 4.1.5 on 2023-03-10 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0013_persona_preferred_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='including_posts', to='graphql_app.category', verbose_name='카테고리'),
        ),
    ]
