# Generated by Django 4.1.5 on 2023-03-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0016_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
