# Generated by Django 4.1.5 on 2023-03-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0017_rename_is_admin_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='body',
            field=models.CharField(max_length=20, unique=True, verbose_name='카테고리 본문'),
        ),
    ]
