# Generated by Django 4.1.5 on 2023-03-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0018_alter_category_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='following_personas',
            field=models.ManyToManyField(related_name='follower_personas', to='graphql_app.persona', verbose_name='팔로우 하고 있는 페르소나 목록'),
        ),
    ]
