# Generated by Django 4.1.5 on 2023-03-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0020_post_read_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(db_column='author_persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='written_posts', to='graphql_app.persona', verbose_name='글쓴이'),
        ),
    ]
