# Generated by Django 4.1.5 on 2023-03-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0021_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': '페르소나', 'verbose_name_plural': '페르소나 목록'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '게시물', 'verbose_name_plural': '게시물 목록'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '사용자 목록'},
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
