# Generated by Django 4.1.5 on 2023-03-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0022_alter_persona_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categorie',
        ),
        migrations.AlterModelTable(
            name='persona',
            table='persona',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
