# Generated by Django 4.1.5 on 2023-03-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0023_alter_category_table_alter_persona_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='introduction',
            field=models.TextField(blank=True, default='자기 소개가 없습니다.', null=True, verbose_name='소개'),
        ),
    ]
