# Generated by Django 4.1.5 on 2023-03-17 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0024_alter_persona_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='free_content',
            field=models.TextField(blank=True, default=None, verbose_name='무료 내용'),
        ),
        migrations.AddField(
            model_name='post',
            name='금액',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=1),
        ),
        migrations.CreateModel(
            name='WaitFreePersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_at', models.DateTimeField(verbose_name='공개 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('persona', models.ForeignKey(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, to='graphql_app.persona', verbose_name='글쓴이')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='graphql_app.post', verbose_name='게시물')),
            ],
        ),
    ]
