# Generated by Django 4.1.5 on 2023-03-17 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0024_alter_persona_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField(verbose_name='티어')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_memberships', to='graphql_app.persona', verbose_name='창작자 페르소나')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_memberships', to='graphql_app.persona', verbose_name='구독자 페르소나')),
            ],
            options={
                'verbose_name': '멤버쉽',
                'verbose_name_plural': '멤버쉽 목록',
                'db_table': 'membership',
            },
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('subscriber', 'creator'), name='unique membership'),
        ),
    ]
