# Generated by Django 4.1.5 on 2023-03-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0025_post_free_content_post_금액_waitfreepersona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='금액',
            new_name='price',
        ),
    ]
