# Generated by Django 4.1.5 on 2023-03-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0026_rename_금액_post_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='free_content',
            new_name='paid_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
    ]
