# Generated by Django 4.1.5 on 2023-03-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0028_alter_post_paid_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='paid_content',
            field=models.TextField(blank=True, default='', null=True, verbose_name='무료 내용'),
        ),
    ]
