# Generated by Django 4.1.5 on 2023-03-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0025_membership_membership_unique membership'),
        ('graphql_app', '0030_alter_waitfreepersona_unique_together_and_more'),
    ]

    operations = [
    ]
