# Generated by Django 4.1.5 on 2023-03-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0031_merge_20230324_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='read_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='persona',
            name='picture_url',
            field=models.URLField(default=None, verbose_name='이미지 파일 주소'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='paid_content',
            field=models.TextField(blank=True, null=True, verbose_name='유료 내용'),
        ),
    ]
