# Generated by Django 4.1.5 on 2023-03-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0032_remove_post_read_count_remove_user_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='required_membership_tier',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='요구 멤버쉽 티어'),
        ),
    ]
