# Generated by Django 4.1.5 on 2023-03-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0033_persona_required_membership_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='required_membership_tier',
        ),
        migrations.AddField(
            model_name='post',
            name='required_membership_tier',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='요구 멤버쉽 티어'),
        ),
    ]
