# Generated by Django 4.1.5 on 2023-03-30 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0035_post_content_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReadingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_count', models.PositiveIntegerField(default=0, verbose_name='읽은 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_app.persona', verbose_name='읽은 페르소나')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_app.post', verbose_name='대상 게시물')),
            ],
            options={
                'verbose_name': '조회 기록',
                'verbose_name_plural': '조회 기록 목록',
                'db_table': 'post_reading_records',
            },
        ),
        migrations.AddConstraint(
            model_name='postreadingrecord',
            constraint=models.UniqueConstraint(fields=('post', 'persona'), name='unique post reading record'),
        ),
    ]
