# Generated by Django 4.1.5 on 2023-04-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0036_postreadingrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreadingrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
