# Generated by Django 4.1.5 on 2023-04-10 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0038_alter_postreadingrecord_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='누른 시각')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_app.persona', verbose_name='누른 페르소나')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_app.post', verbose_name='대상 게시물')),
            ],
            options={
                'verbose_name': '좋아요',
                'verbose_name_plural': '좋아요 목록',
                'db_table': 'post_like',
            },
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('post', 'persona'), name='unique post persona like'),
        ),
    ]
