# Generated by Django 4.1.5 on 2023-04-12 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0038_alter_postreadingrecord_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='챌린지 제목')),
                ('description', models.TextField(verbose_name='챌린지 설명')),
                ('max_persona_count', models.PositiveIntegerField(verbose_name='최대 참여 인원')),
                ('is_open', models.BooleanField(default=False, verbose_name='모집 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신 시각')),
                ('personas', models.ManyToManyField(to='graphql_app.persona', verbose_name='참여 페르소나 목록')),
            ],
            options={
                'verbose_name': '챌린지',
                'verbose_name_plural': '챌린지 목록',
                'db_table': 'challenges',
            },
        ),
        migrations.CreateModel(
            name='ChallengeObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='목표 제목')),
                ('kind', models.CharField(max_length=10, verbose_name='종류')),
                ('duration_type', models.CharField(max_length=10, verbose_name='기간 타입')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_app.challenge', verbose_name='챌린지')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_app.challenge', verbose_name='챌린지')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_app.persona', verbose_name='페르소나')),
            ],
            options={
                'verbose_name': '챌린지 참여 기록',
                'verbose_name_plural': '챌린지 참여 기록 목록',
                'db_table': 'challenge_histories',
            },
        ),
    ]
