# Generated by Django 4.1.5 on 2023-04-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0039_bookmark_bookmark_unique post boormark'),
        ('graphql_app', '0039_postlike_postlike_unique post persona like'),
    ]

    operations = [
    ]
