# Generated by Django 4.1.5 on 2023-04-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0040_alter_challengeobjective_duration_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeobjective',
            name='duration_type',
            field=models.CharField(choices=[('monthly', '매달'), ('weekly', '매주'), ('daily', '매일')], max_length=10, verbose_name='기간 타입'),
        ),
        migrations.AlterField(
            model_name='challengeobjective',
            name='kind',
            field=models.CharField(choices=[('individual', '개인'), ('together', '공동')], max_length=10, verbose_name='종류'),
        ),
    ]
