# Generated by Django 4.1.5 on 2023-04-13 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0042_alter_challengeobjective_duration_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challengeobjective',
            options={'verbose_name': '챌린지 목표'},
        ),
        migrations.RemoveField(
            model_name='challengehistory',
            name='challenge',
        ),
        migrations.AddField(
            model_name='challengehistory',
            name='challenge_objective',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='graphql_app.challengeobjective', verbose_name='챌린지 목표'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='challengeobjective',
            table='challenge_objective',
        ),
    ]
