# Generated by Django 4.1.5 on 2023-04-13 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0043_alter_challengeobjective_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='challengeobjective',
            table='challenge_objectives',
        ),
    ]
