# Generated by Django 4.1.5 on 2023-04-13 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0044_alter_challengeobjective_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChallengeHistory',
        ),
        migrations.CreateModel(
            name='ChallengeObjectiveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_done_at', models.DateTimeField(verbose_name='완료한 시각')),
                ('is_done', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('challenge_objective_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_app.challengeobjective',
                                   verbose_name='챌린지 목표')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_app.persona',
                                              verbose_name='페르소나')),
            ],
            options={
                'verbose_name': '챌린지 참여 기록',
                'verbose_name_plural': '챌린지 참여 기록 목록',
                'db_table': 'challenge_histories',
            },
        ),
        migrations.AddConstraint(
            model_name='challengeobjectivehistory',
            constraint=models.UniqueConstraint(fields=('challenge_objective_id', 'persona'), name='unique challenge_objective and persona'),
        ),
    ]
