# Generated by Django 4.1.5 on 2023-04-13 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0045_challengeobjectivehistory_delete_challengehistory_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='challengeobjectivehistory',
            table='challenge_objective_histories',
        ),
    ]
