# Generated by Django 4.1.5 on 2023-04-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0046_alter_challengeobjectivehistory_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeobjectivehistory',
            name='last_done_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='완료한 시각'),
        ),
    ]
