# Generated by Django 4.1.5 on 2023-04-14 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0047_alter_challengeobjectivehistory_last_done_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengeobjectivehistory',
            old_name='challenge_objective_id',
            new_name='challenge_objective',
        ),
    ]
