# Generated by Django 4.1.5 on 2023-04-14 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0040_merge_20230412_1420'),
        ('graphql_app', '0048_rename_challenge_objective_id_challengeobjectivehistory_challenge_objective'),
    ]

    operations = [
    ]
