# Generated by Django 4.1.5 on 2023-04-18 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0049_merge_20230414_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_app.persona', verbose_name='페르소나')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphql_app.post', verbose_name='게시물')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글 목록',
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
