# Generated by Django 4.1.5 on 2023-04-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0050_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.CharField(default='', max_length=200, verbose_name='댓글 본문g'),
            preserve_default=False,
        ),
    ]
