# Generated by Django 4.1.5 on 2023-05-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0051_comment_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='age',
        ),
        migrations.AddField(
            model_name='persona',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='생년'),
        ),
    ]
