export const imagePath: {[key: string]: any} = {
  eye_off: require('../assets/eye-off.png'),
  eye: require('../assets/eye.png'),
  check: require('../assets/check.png'),
  avatar: require('../assets/profileImg.png'),
  searchIcon: require('../assets/search-white.png'),
  sampleStat: require('../assets/sample_stat.png'),
  background: require('../assets/background1.png'),
  settingIcon: require('../assets/setting.png'),
  shareIcon: require('../assets/share.png'),
  editIcon: require('../assets/edit.png'),
  moreIcon: require('../assets/more-image.png'),
  welcome: require('../assets/welcome.png'),
  reportIcon: require('../assets/report.png'),
  cancel: require('../assets/cancel.png'),
  backBtn: require('../assets/back_btn.png'),
  dropdownBtn: require('../assets/dropdownIcon.png'),
  lockIcon: require('../assets/lockIcon.png'),
};
