# Generated by Django 4.1.5 on 2023-01-25 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신 시각')),
                ('nickname', models.CharField(max_length=20, unique=True, verbose_name='닉네임')),
                ('introduction', models.TextField(blank=True, default='자기 소개가 없습니다.', verbose_name='소개')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('gender', models.CharField(choices=[('ML', '남성'), ('FM', '여성')], default=None, max_length=2, null=True, verbose_name='성별')),
                ('age_group', models.IntegerField(choices=[(1, ' 10'), (2, ' 20'), (3, ' 30'), (4, ' 40'), (5, ' 50'), (6, 'Elder')], default=None, null=True, verbose_name='연령대')),
                ('job', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='직업')),
                ('is_certified', models.BooleanField(default=False, verbose_name='공인 여부')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='대상 사용자')),
            ],
            options={
                'verbose_name': '구독 페르소나',
                'verbose_name_plural': '구독 페르소나 목록',
                'db_table': 'personas',
            },
        ),
    ]
