# Generated by Django 4.1.5 on 2023-01-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='age_group',
            field=models.IntegerField(choices=[(0, 'None'), (1, ' 10'), (2, ' 20'), (3, ' 30'), (4, ' 40'), (5, ' 50'), (6, 'Elder')], default=None, null=True, verbose_name='연령대'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='gender',
            field=models.CharField(choices=[('NO', '미입력'), ('ML', '남성'), ('FM', '여성')], default=None, max_length=2, null=True, verbose_name='성별'),
        ),
    ]
