export const examplefeedcard = [
  {
    feed_id: 1,
    title: '반려동물: 우린 왜 고양이를 까칠하다고 생각할까?',
    author: '홍현지',
    author_id: '@hongs_0430',
    author_img: String(require('../assets/profileImg.png')),
    content:
      "무관심하고 까칠하다는 이미지는 사라지지 않는 것일까. 어느 정도 사실인 부분도 있을까. 고양이가 '독립적'이라는 인식에도, 반려동물로서의 인기는 사그라들지 않는다.",
    like: 16,
    bookmark: 16,
    comment: 3,
    hash_tag: ['대학', '조별과제'],
    like_check: true,
    bookmark_check: false,
  },
  {
    feed_id: 2,
    title: '반려동물: 우린 왜 고양이를 까칠하다고 생각할까?',
    author: '홍현지',
    author_id: '@hongs_0430',
    author_img: String(require('../assets/profileImg.png')),
    content:
      "무관심하고 까칠하다는 이미지는 사라지지 않는 것일까. 어느 정도 사실인 부분도 있을까. 고양이가 '독립적'이라는 인식에도, 반려동물로서의 인기는 사그라들지 않는다.",
    like: 16,
    bookmark: 16,
    comment: 3,
    hash_tag: ['대학', '조별과제'],
    like_check: true,
    bookmark_check: false,
  },
  {
    feed_id: 3,
    title: '반려동물: 우린 왜 고양이를 까칠하다고 생각할까?',
    author: '홍현지',
    author_id: '@hongs_0430',
    author_img: String(require('../assets/profileImg.png')),
    content:
      "무관심하고 까칠하다는 이미지는 사라지지 않는 것일까. 어느 정도 사실인 부분도 있을까. 고양이가 '독립적'이라는 인식에도, 반려동물로서의 인기는 사그라들지 않는다.",
    like: 16,
    bookmark: 16,
    comment: 3,
    hash_tag: ['대학', '조별과제'],
    like_check: true,
    bookmark_check: false,
  },
];
